"""
Document processing coordinator.

This module provides the Processor class, which routes documents
that require format-specific processing to the appropriate processor.
"""

# LangChain Document structure
from langchain_core.documents import Document

# Import the specialized processors
from .notebook import NotebookProcessor

class Processor:
    """
    Process documents that require format-specific transformations.
        - Documents that do not require processing are returned unchanged.
        - Jupyter Notebook documents are delegated to their
          corresponding specialized processor.
    """

    def __init__(self):
        # Defined the specialized processors
        self._notebook_processor = NotebookProcessor()

    def process(self, documents: list[Document]) -> list[Document]:
        """
        Process a list of documents.

        Args:
            documents: list[Document]
                Documents produced by the ingestion stage.

        Returns:
            A list containing the unchanged documents that did not
            require processing and the documents generated by the
            specialized processors.
        """
        processed_documents: list[Document] = []

        for document in documents:
            file_type = document.metadata.get("file_type")

            # Delegate notebook documents to the specialized processor.
            # Other document types are passed through unchanged.
            if file_type == ".ipynb":
                processed_documents.extend(
                    self._notebook_processor.process(document)
                )
            else:
                processed_documents.append(document)

        return processed_documents