"""
Markdown document chunker.

This module provides the MarkdownChunker class, which splits Markdown
documents by headers before applying recursive character-based chunking.
"""

# Document Langchain structure
from langchain_core.documents import Document

# LangChain chunking tools 
from langchain_text_splitters import (
    MarkdownHeaderTextSplitter,
    RecursiveCharacterTextSplitter,
)

# Chunk global configuration
from .chunkConfig import DEFAULT_CHUNK_SIZE, DEFAULT_CHUNK_OVERLAP

# Markdown header levels used to identify document sections.
MARKDOWN_HEADERS = [
    ("#", "header_1"),
    ("##", "header_2"),
    ("###", "header_3"),
]

class MarkdownChunker:
    """
    Split Markdown documents using headers and recursive character splitting.

    Markdown headers are preserved both in the chunk content and in the
    chunk metadata.
    """

    def __init__(
        self,
        chunk_size: int = DEFAULT_CHUNK_SIZE,
        chunk_overlap: int = DEFAULT_CHUNK_OVERLAP,
    ):
        # Store the chunking configuration.
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap

        # First split the Markdown document into sections based on headers.
        # strip_headers=False keeps the headers in the resulting content.
        self._header_splitter = MarkdownHeaderTextSplitter(
            headers_to_split_on=MARKDOWN_HEADERS,
            strip_headers=False,
        )

        # Recursively split sections that are larger than the configured
        # chunk size.
        self._recursive_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
        )

    def chunk(self, document: Document) -> list[Document]:
        """
        Split a Markdown document into smaller chunks.

        Markdown sections are first identified using headers. Each section
        is then recursively split if it exceeds the configured chunk size.

        If the document contains no Markdown headers, the entire document
        is processed directly by the recursive splitter.

        Args:
            document: Markdown document to split.

        Returns:
            A list of chunked Documents.
        """

        # Split the document into sections based on Markdown headers.
        markdown_documents = self._header_splitter.split_text(
            document.page_content
        )

        # Return an empty list if the document contains no content.
        if not markdown_documents:
            return []

        # If headers were detected, recursively split each section.
        if self._has_headers(markdown_documents):
            return self._chunk_sections(
                markdown_documents=markdown_documents,
                document=document,
            )

        # Without headers, fall back to standard recursive chunking.
        return self._recursive_splitter.split_documents([document])

    def _chunk_sections(
        self,
        markdown_documents: list[Document],
        document: Document,
    ) -> list[Document]:
        """
        Recursively split Markdown sections while preserving their headers.

        Each section is first combined with the original document metadata
        and then passed to the recursive splitter.
        """

        chunks: list[Document] = []

        for section in markdown_documents:
            # Combine the original metadata with the header metadata
            # generated by MarkdownHeaderTextSplitter.
            section_document = self._build_section_document(
                section=section,
                original_document=document,
            )
            
            # Split the section if it exceeds the configured chunk size.
            # The resulting chunks inherit the section and original metadata.
            section_chunks = self._recursive_splitter.split_documents(
                [section_document]
            )

            chunks.extend(section_chunks)

        return chunks

    @staticmethod
    def _build_section_document(
        section: Document,
        original_document: Document,
    ) -> Document:
        """
        Build a section Document with headers in content and metadata.

        The original metadata is preserved and combined with the metadata
        generated by the Markdown header splitter.
        """

        # Start with the original metadata and add the section metadata.
        metadata = {
            **original_document.metadata,
            **section.metadata,
        }

        return Document(
            page_content=section.page_content,
            metadata=metadata,
        )

    @staticmethod
    def _has_headers(
        markdown_documents: list[Document],
    ) -> bool:
        """
        Check whether the Markdown splitter detected any headers.
        """
        return any(
            key in document.metadata
            for document in markdown_documents
            for _, key in MARKDOWN_HEADERS
        )